package com.foundstone.s3i.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="customerOrderItemForm" 
 */
public class CustomerOrderItemForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected String id;

    protected String product;

    protected String taxPercentage;

    protected String totalSalePrice;

    protected String uid;

    /** Default empty constructor. */
    public CustomerOrderItemForm() {}

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

    public String getProduct()
    {
        return this.product;
    }
   /**
    */

    public void setProduct( String product )
    {
        this.product = product;
    }

    public String getTaxPercentage()
    {
        return this.taxPercentage;
    }
   /**
    */

    public void setTaxPercentage( String taxPercentage )
    {
        this.taxPercentage = taxPercentage;
    }

    public String getTotalSalePrice()
    {
        return this.totalSalePrice;
    }
   /**
    */

    public void setTotalSalePrice( String totalSalePrice )
    {
        this.totalSalePrice = totalSalePrice;
    }

    public String getUid()
    {
        return this.uid;
    }
   /**
    */

    public void setUid( String uid )
    {
        this.uid = uid;
    }

        /* To add non XDoclet-generated methods, create a file named
           actionform-methods-CustomerOrderItemForm.java
           containing the additional code and place it in your merge dir.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
