package com.foundstone.s3i.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="customerOrderForm" 
 */
public class CustomerOrderForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected String bankAccountNumber;

    protected String creditCardNumber;

    protected String expiration;

    protected String id;

    protected String magicCoupon;

    protected transient java.util.List orderEntries = new java.util.ArrayList();

    protected String orderNumber;

    protected String paymentType;

    protected String salesTax;

    protected String shipped;

    protected String total;

    protected String totalAmount;

    protected String user;

    /** Default empty constructor. */
    public CustomerOrderForm() {}

    public String getBankAccountNumber()
    {
        return this.bankAccountNumber;
    }
   /**
    */

    public void setBankAccountNumber( String bankAccountNumber )
    {
        this.bankAccountNumber = bankAccountNumber;
    }

    public String getCreditCardNumber()
    {
        return this.creditCardNumber;
    }
   /**
    */

    public void setCreditCardNumber( String creditCardNumber )
    {
        this.creditCardNumber = creditCardNumber;
    }

    public String getExpiration()
    {
        return this.expiration;
    }
   /**
    */

    public void setExpiration( String expiration )
    {
        this.expiration = expiration;
    }

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

    public String getMagicCoupon()
    {
        return this.magicCoupon;
    }
   /**
    */

    public void setMagicCoupon( String magicCoupon )
    {
        this.magicCoupon = magicCoupon;
    }

    public java.util.List getOrderEntries()
    {
        return this.orderEntries;
    }
   /**
    */

    public void setOrderEntries( java.util.List orderEntries )
    {
        this.orderEntries = orderEntries;
    }

    public String getOrderNumber()
    {
        return this.orderNumber;
    }
   /**
    */

    public void setOrderNumber( String orderNumber )
    {
        this.orderNumber = orderNumber;
    }

    public String getPaymentType()
    {
        return this.paymentType;
    }
   /**
    * @struts.validator type="required"
    */

    public void setPaymentType( String paymentType )
    {
        this.paymentType = paymentType;
    }

    public String getSalesTax()
    {
        return this.salesTax;
    }
   /**
    */

    public void setSalesTax( String salesTax )
    {
        this.salesTax = salesTax;
    }

    public String getShipped()
    {
        return this.shipped;
    }
   /**
    */

    public void setShipped( String shipped )
    {
        this.shipped = shipped;
    }

    public String getTotal()
    {
        return this.total;
    }
   /**
    */

    public void setTotal( String total )
    {
        this.total = total;
    }

    public String getTotalAmount()
    {
        return this.totalAmount;
    }
   /**
    */

    public void setTotalAmount( String totalAmount )
    {
        this.totalAmount = totalAmount;
    }

    public String getUser()
    {
        return this.user;
    }
   /**
    */

    public void setUser( String user )
    {
        this.user = user;
    }

        /* To add non XDoclet-generated methods, create a file named
           actionform-methods-CustomerOrderForm.java
           containing the additional code and place it in your merge dir.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
