package com.foundstone.s3i.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="feedbackForm" 
 */
public class FeedbackForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected String parent;

    protected String feedback;

    protected String id;

    /** Default empty constructor. */
    public FeedbackForm() {}

    public String getParent()
    {
        return this.parent;
    }
   /**
    */

    public void setParent( String parent )
    {
        this.parent = parent;
    }

    public String getFeedback()
    {
        return this.feedback;
    }
   /**
    */

    public void setFeedback( String feedback )
    {
        this.feedback = feedback;
    }

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

        /* To add non XDoclet-generated methods, create a file named
           actionform-methods-FeedbackForm.java
           containing the additional code and place it in your merge dir.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
