package com.foundstone.s3i.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="productForm" 
 */
public class ProductForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected transient java.util.List feedback = new java.util.ArrayList();

    protected String author;

    protected String category;

    protected String description;

    protected String id;

    protected String isbn;

    protected String popularity;

    protected String price;

    protected String publisher;

    protected String quantity;

    protected String title;

    protected String vendor;

    protected String uid;

    protected String keyWords;

    protected String imgUrl;

    /** Default empty constructor. */
    public ProductForm() {}

    public java.util.List getFeedback()
    {
        return this.feedback;
    }
   /**
    */

    public void setFeedback( java.util.List feedback )
    {
        this.feedback = feedback;
    }

    public String getAuthor()
    {
        return this.author;
    }
   /**
    */

    public void setAuthor( String author )
    {
        this.author = author;
    }

    public String getCategory()
    {
        return this.category;
    }
   /**
    */

    public void setCategory( String category )
    {
        this.category = category;
    }

    public String getDescription()
    {
        return this.description;
    }
   /**
    */

    public void setDescription( String description )
    {
        this.description = description;
    }

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

    public String getIsbn()
    {
        return this.isbn;
    }
   /**
    */

    public void setIsbn( String isbn )
    {
        this.isbn = isbn;
    }

    public String getPopularity()
    {
        return this.popularity;
    }
   /**
    */

    public void setPopularity( String popularity )
    {
        this.popularity = popularity;
    }

    public String getPrice()
    {
        return this.price;
    }
   /**
    */

    public void setPrice( String price )
    {
        this.price = price;
    }

    public String getPublisher()
    {
        return this.publisher;
    }
   /**
    */

    public void setPublisher( String publisher )
    {
        this.publisher = publisher;
    }

    public String getQuantity()
    {
        return this.quantity;
    }
   /**
    */

    public void setQuantity( String quantity )
    {
        this.quantity = quantity;
    }

    public String getTitle()
    {
        return this.title;
    }
   /**
    */

    public void setTitle( String title )
    {
        this.title = title;
    }

    public String getVendor()
    {
        return this.vendor;
    }
   /**
    */

    public void setVendor( String vendor )
    {
        this.vendor = vendor;
    }

    public String getUid()
    {
        return this.uid;
    }
   /**
    */

    public void setUid( String uid )
    {
        this.uid = uid;
    }

    public String getKeyWords()
    {
        return this.keyWords;
    }
   /**
    */

    public void setKeyWords( String keyWords )
    {
        this.keyWords = keyWords;
    }

    public String getImgUrl()
    {
        return this.imgUrl;
    }
   /**
    */

    public void setImgUrl( String imgUrl )
    {
        this.imgUrl = imgUrl;
    }

        /* To add non XDoclet-generated methods, create a file named
           actionform-methods-ProductForm.java
           containing the additional code and place it in your merge dir.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
