matrix:
  include:
    - language: java
      openjdk: 11
      before_script:
        - cd HackmeBooks2/hackmebooks2-back/
    - language: node_js
      node_js:
        - 10
      before_script:
        - cd HackmeBooks2/hackmebooks2-front/
        - npm install

